# Generated by Django 5.2.15 on 2026-06-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'brand', 'verbose_name_plural': 'brands'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='productconfiguration',
            options={'verbose_name': 'product_configuration', 'verbose_name_plural': 'product_configurations'},
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={'verbose_name': 'product_item', 'verbose_name_plural': 'product_items'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'variation', 'verbose_name_plural': 'variations'},
        ),
        migrations.AlterModelOptions(
            name='variationoption',
            options={'verbose_name': 'variation_option', 'verbose_name_plural': 'variation_options'},
        ),
    ]
