# Generated by Django 5.2.15 on 2026-06-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'order_line', 'verbose_name_plural': 'order_lines'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'order_status', 'verbose_name_plural': 'order_statuses'},
        ),
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'verbose_name': 'shipping_method', 'verbose_name_plural': 'shipping_methods'},
        ),
    ]
