# Generated by Django 5.2.15 on 2026-06-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'cart_item', 'verbose_name_plural': 'cart_items'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'verbose_name': 'shopping_cart', 'verbose_name_plural': 'shopping_carts'},
        ),
    ]
