# Generated by Django 5.2.15 on 2026-06-16 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'discount_types',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('is_exclusive', models.BooleanField(db_index=True, default=False)),
                ('discount_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='promotions.discounttype')),
            ],
            options={
                'db_table': 'promotions',
            },
        ),
        migrations.CreateModel(
            name='PromotionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_categories', to='catalog.category')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_categories', to='promotions.promotion')),
            ],
            options={
                'db_table': 'promotion_categories',
                'constraints': [models.UniqueConstraint(fields=('promotion', 'category'), name='promotion_categories_promotion_category_unique')],
            },
        ),
        migrations.CreateModel(
            name='PromotionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_users', to='promotions.promotion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promotion_users',
                'constraints': [models.UniqueConstraint(fields=('promotion', 'user'), name='promotion_users_promotion_user_unique')],
            },
        ),
    ]
