# Generated by Django 5.2.15 on 2026-06-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discounttype',
            options={'verbose_name': 'discount_type', 'verbose_name_plural': 'discount_types'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'promotion', 'verbose_name_plural': 'promotions'},
        ),
        migrations.AlterModelOptions(
            name='promotioncategory',
            options={'verbose_name': 'promotion_category', 'verbose_name_plural': 'promotion_categories'},
        ),
        migrations.AlterModelOptions(
            name='promotionuser',
            options={'verbose_name': 'promotion_user', 'verbose_name_plural': 'promotion_users'},
        ),
    ]
