# Generated by Django 5.2.15 on 2026-06-20 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inventoryledgerentry',
            name='inventory_ledger_quantity_change_nonzero',
        ),
        migrations.RemoveConstraint(
            model_name='inventoryledgerentry',
            name='inventory_ledger_balances_match',
        ),
        migrations.RemoveIndex(
            model_name='inventoryledgerentry',
            name='inventory_item_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventoryledgerentry',
            name='inventory_order_reason_idx',
        ),
        migrations.AlterField(
            model_name='inventoryledgerentry',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_ledger_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryledgerentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventoryledgerentry',
            name='quantity_after',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryledgerentry',
            name='quantity_before',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='inventoryledgerentry',
            name='reason',
            field=models.CharField(choices=[('initial_stock', 'Initial stock'), ('manual_adjustment', 'Manual adjustment'), ('checkout', 'Checkout'), ('order_cancelled', 'Order cancelled'), ('payment_failed', 'Payment failed'), ('return_approved', 'Return approved'), ('order_refunded', 'Order refunded')], max_length=40),
        ),
    ]
