# Generated by Django 5.2.15 on 2026-06-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'payment_method', 'verbose_name_plural': 'payment_methods'},
        ),
        migrations.AlterModelOptions(
            name='paymentstatus',
            options={'verbose_name': 'payment_status', 'verbose_name_plural': 'payment_statuses'},
        ),
    ]
