# Generated by Django 5.2.15 on 2026-06-16 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistitem',
            options={'verbose_name': 'user_favorite', 'verbose_name_plural': 'user_favorites'},
        ),
    ]
